### PR TITLE
Upgrading to Laravel 6

### PR DESCRIPTION
**Pull request by alouini333**
#21

### CODE REVIEW

**Comment by lancepioch** [comment]
@alouini333 holy smokes, thank you so much! I’ll test this week, but initially it looks good so far that I’ve seen!

**Comment by alouini333** [comment]
@lancepioch you are welcome, I will be waiting for your feedback

**Comment by lancepioch** [comment]
@alouini333 We need to fix the tests. I'll give it a go, but feel free to push up extra commits that help resolve the tests running successfully.

**Comment by lancepioch** [comment]
Honestly I messed up the pull request and Github won't let me reopen it, so I'm creating a new one.

**Pull request closed without merging**
